import type { GetStaticProps, NextPage } from "next";
import Head from "next/head";
import { Tooltip } from "react-tiny-tooltip";

const Home: NextPage<{ code: string }> = ({ code }) => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="px-10">
        <h1 className="text-center text-8xl font-extrabold mt-14">
          React tiny tooltip
        </h1>
        <p className="text-xl text-center text-slate-700 mt-10">
          A simple, tiny, accessible, opinionated and lightweight tooltip
          library for React. Built with Stitches and Radix UI.
        </p>
        <div className="my-16 text-center">
          <Tooltip content="Hello there" side="top">
            <button className="text-2xl font-extrabold underline">
              Hover here!
            </button>
          </Tooltip>
        </div>

        <p className="text-center mb-5">
          It&apos;s soo simple - Just import and use.{" "}
        </p>
        <Tooltip content="Here's the code for the above example">
          <div
            className="max-w-3xl mx-auto"
            dangerouslySetInnerHTML={{ __html: code }}
          />
        </Tooltip>
      </main>
    </div>
  );
};

export default Home;

export const getStaticProps: GetStaticProps = async () => {
  const shiki = require("shiki");

  const DEMO_CODE = `
import React from 'react';
import { Tooltip } from 'react-tiny-tooltip';

export default () => (
	<div>
		// \`content\` can be a React element too!
		<Tooltip content="Hello there" side="top">
			<button className="text-2xl font-extrabold underline">
				Hover here!
			</button>
		</Tooltip>
	</div>
);
`;

  const highlighter = await shiki.getHighlighter({
    theme: "material-palenight",
  });

  const code = highlighter.codeToHtml(DEMO_CODE, {
    lang: "js",
  });

  return {
    props: {
      code: code,
    },
  };
};
